plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/ubuntu/.openclaw/workspace/fireplace-lead-gen/site"
publishOrigin = "default"
base = "/home/ubuntu/.openclaw/workspace/fireplace-lead-gen/site"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]